services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "15061007"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "nwc_db"
    volumes:
      - ./pgdata/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: nwc
    depends_on:
      - db
    ports:
      - "4000:4000"
